liip_imagine:
    filter_sets:
        # name our filter set "my_crop_filter"
        icsCelebritySquare:
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
        icsCelebrityThumbnail:
            filters:
                thumbnail:
                    size: [128, ~]
                    mode: outbound